### ISSUE TITLE
Changes to PATH variable not recognized by the msys2 shell

### ISSUE THREAD

**Issue by hakonhagland** [msys2/setup-msys2#106]
I am trying to install a Perl module installer called [cpanm](https://metacpan.org/pod/App::cpanminus). Here, is my workflow file (simplified for debugging purposes):
```
name: windows-msys2
on: [push, pull_request]
jobs:
  build-dist:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: minimal
          install: base-devel
      - uses: actions/checkout@v2
      - name: setup perl locallib
        run: |
          TOPDIR=$(cygpath "$GITHUB_WORKSPACE")
          PERL_LOCAL_LIB_ROOT="$TOPDIR/perl5"
          >>"$GITHUB_ENV" echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT"
          >>"$GITHUB_ENV" echo "PERL5LIB=$PERL_LOCAL_LIB_ROOT/lib/perl5"
          >>"$GITHUB_ENV" echo "PERL_MB_OPT=--install_base \"$PERL_LOCAL_LIB_ROOT/\""
          >>"$GITHUB_ENV" echo "PERL_MM_OPT=INSTALL_BASE=$PERL_LOCAL_LIB_ROOT"
          >>"$GITHUB_ENV" echo "PATH=$PERL_LOCAL_LIB_ROOT/bin:$PATH"
      - name: install cpanm
        run: |
          echo "PATH=$PATH"
          cpan App::cpanminus  # This command installs cpanm
          export PATH
          ls -l $PERL_LOCAL_LIB_ROOT/bin/cpanm
      - name: test cpanm
        run: |
          ls -l $PERL_LOCAL_LIB_ROOT/bin/cpanm
          export PATH
          cpanm -v Path::Tiny
```
Here is a [link](https://github.com/hakonhagland/msys2-gha-path-test/runs/1792855140?check_suite_focus=true) to the log for failed workflow run.

As can be seen, the step *"install cpanm"* installs the executable script `cpanm` into the directory `/d/a/msys2-gha-path-test/msys2-gha-path-test/perl5/bin` and in step *"test cpanm"* `ls -l` shows that the script exists in the correct directory. Also `PATH` is exported and contains:
```
PATH: /d/a/msys2-gha-path-test/msys2-gha-path-test/perl5/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

Notice that the first entry in `PATH` is the directory where the script `cpanm` is installed.

Still, when the runner executes the next command `cpanm -v Path::Tiny` it fails with
```
D:\a\_temp\fee6b146-c300-4100-800d-0ad7b7e626b2: line 3: cpanm: command not found
15
Error: Process completed with exit code 127.
```
What can be the problem here?

**Comment by eine** [comment]
That is the default behaviour of MSYS2: the environment/PATH are not inherited. See https://github.com/msys2/setup-msys2#path-type, #98 and #104.

**Comment by hakonhagland** [comment]
> the environment/PATH are not inherited.

@eine Thanks! So you cannot export  the PATH to the next step via GITHUB_ENV like I did. You need to reconstruct and set the PATH manually at each step? What is confusing is that you *can* use GITHUB_ENV to export PATH to next step on linux and macOS runners, but on MSYS2 it does not work.

**Comment by eine** [comment]
Please, see the references I provided.

> You need to reconstruct and set the PATH manually at each step?

This is explained in https://github.com/msys2/setup-msys2#path-type. You don't need to, but it is recommended.

> What is confusing is that you can use GITHUB_ENV to export PATH to next step on linux and macOS runners, but on MSYS2 it does not work.

See #98 and #104.
