### ISSUE TITLE
'mingw32-make' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Jiangshan00001** [msys2/setup-msys2#113]
after add this :
    - name: install correct version of mingw
      uses:  msys2/setup-msys2@v2
      with: 
           msystem: MINGW32
           path-type: minimal

when i build some problem, it said:
'mingw32-make' is not recognized as an internal or external command,
why?

i have added shell: msys2 {0} in the step.

    - name: configure-pkt_sim
      shell: msys2 {0}
      run: ./pkt_sim.config.bat 5.9

**Comment by lazka** [comment]
you need to install mingw-w64-i686-make

**Comment by Jiangshan00001** [comment]
thanks
