### ISSUE TITLE
"command not found" when trying to call CMake or GCC after installing them

### ISSUE THREAD

**Issue by silvioprog** [msys2/setup-msys2#118]
Hi.

Consider following all steps available at the official [MSYS2 web site](https://www.msys2.org). After finishing them, install the CMake and GCC (I have been trying the i686 option):

```
$ pacman -S mingw-w64-i686-cmake mingw-w64-i686-gcc
```

Now, try to use CMake:

```
$ cmake
bash: cmake: command not found
```

or GCC:

```
$ gcc
bash: gcc: command not found
```

These commands worked in previous versions of MSYS, so I'm not sure if it is a bug in MSYS of something wrong I'm doing. 😕

TIA for any help!

**Comment by Biswa96** [comment]
You have to use proper shell, here MINGW32 (grey icon).

**Comment by silvioprog** [comment]
@Biswa96 It worked like a charm! 🤩

It seems the old menu option `MSYS2 MSYS` is new `MSYS2 MinGW 32-bit` (or `MSYS2 MinGW 64-bit` for 64-bit) in the new versions.

Thank very much for answering so quickly!

**Comment by eine** [comment]
@silvioprog with regard to "the old menu option", I think it might be related to [March 15, 2021 8:19 AM](https://gitter.im/msys2/msys2?at=604f0a7d22a5ce4a915861b2). As @Biswa96 said, you now need to execute the gray or blue icons (entrypoints) explicitly.
