### ISSUE TITLE
Support MSYSTEM=UCRT64

### ISSUE THREAD

**Issue by szhorvat** [msys2/setup-msys2#125]
This is a request to support UCRT64 packages. 

Currently, setting `msystem `to `UCRT64` gives:

```
Error: 'msystem' needs to be one of MSYS, MINGW32, MINGW64, got UCRT64
```

**Comment by lazka** [comment]
sounds good

**Comment by eine** [comment]
This was tested in https://github.com/msys2/setup-msys2/actions/runs/760606594 but it seems to fail for no obvious reason. `env | grep MSYSTEM` does work, but `env | grep MINGW` crashes. Locally, execution is correct:

```
grep MSYSTEM
MSYSTEM=UCRT64
MSYSTEM_CARCH=x86_64
MSYSTEM_CHOST=x86_64-w64-mingw32
MSYSTEM_PREFIX=/ucrt64
grep MINGW
MINGW_PREFIX=/ucrt64
MINGW_CHOST=x86_64-w64-mingw32
MINGW_PACKAGE_PREFIX=mingw-w64-ucrt-x86_64
```

**Comment by lazka** [comment]
needs a new installer I think

**Comment by lazka** [comment]
should work now

**Comment by eine** [comment]
A new release of the action was just published. @szhorvat, rerunning your workfow should pass now, as long as you are using `v2`.

**Comment by lazka** [comment]
Thanks!

**Comment by szhorvat** [comment]
> rerunning your workfow should pass now, as long as you are using `v2`.

It does, thanks for enabling this!
