### ISSUE TITLE
Using MSVC compiler with msys

### ISSUE THREAD

**Issue by xmunoz** [msys2/setup-msys2#133]
I've been having trouble configuring my windows build to use the Visual Studio compiler (`cl`) in an msys shell. I've tried a variety of configurations and PATH manipulations, but nothing seems to work. Example workflow:
```
- name: Run batch file and set path
  run: | 
    C:\"Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
    echo "/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    which cl # returns the correct path
- uses: msys2/setup-msys2@v2
  with:
    update: true
    install: >-
      base-devel
      git
    path-type: inherit
- name: Build project
  run: |
    ./coinbrew/coinbrew build my-repo
  shell: msys2 {0}
```

Running this workflow errors because it [can't find the compiler](https://github.com/coin-or/CoinUtils/runs/2504819396?check_suite_focus=true):

```
checking for icl... no
checking for cl... no
configure: error: Neither MS nor Intel C compiler found in PATH and CC is unset.
Error: Process completed with exit code 1.
```

I've confirmed that the PATH is being preserved with the `inherit` parameter, but for some reason my program can't seem to find the compiler. This [configuration](https://github.com/coin-or/CoinUtils/blob/master/appveyor.yml#L67) work fine on [AppVeyor](https://ci.appveyor.com/project/coin-or/coinutils/builds/38971305/job/10g06d46hpw0po8q#L100).

**Comment by 1480c1** [comment]
you need to set `CC=cl CXX=cl` and you will need to worry about link.exe

**Comment by 1480c1** [comment]
In the `run:` section, if you do `which cl` and `cl /?`, does it print out the correct path and print out a help message?

**Comment by xmunoz** [comment]
Yes, after I run the batch file the outputs of both are correct, but when I run the compile I'm now getting the following error in config.log
```
cl : Command line warning D9002 : ignoring unknown option '-qversion'
cl : Command line error D8003 : missing source filename
configure:3339: $? = 2
configure:3359: checking whether the C compiler works
configure:3381: /d/a/CoinUtils/CoinUtils/Data/Sample/compile cl -nologo -DNDEBUG -O2 -MD    conftest.c  >&5
conftest.c
LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'
configure:3385: $? = 2
configure:3423: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Sample"
| #define PACKAGE_TARNAME "coin-or-sample"
| #define PACKAGE_VERSION "trunk"
| #define PACKAGE_STRING "Sample trunk"
| #define PACKAGE_BUGREPORT "buildtools@list.coin-or.org"
| #define PACKAGE_URL "https://github.com/coin-or-tools/Data-Sample"
| #define SAMPLE_VERSION "trunk"
| #define SAMPLE_VERSION_MAJOR 9999
| #define SAMPLE_VERSION_MINOR 9999
| #define SAMPLE_VERSION_RELEASE 9999
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3428: error: in `/d/a/CoinUtils/CoinUtils/build/Data/Sample/master':
configure:3430: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by xmunoz** [comment]
> you will need to worry about link.exe

I'm not sure what this means.

**Comment by 1480c1** [comment]
Feels like you might need to pass the proper `LIBS` or something like `LIB_PATH` (I don't remember what msvc called it, but it seems that's not autofilled unless you are using visual studio)

**Comment by 1480c1** [comment]
> > you will need to worry about link.exe
> 
> I'm not sure what this means.

GNU provides a link.exe but the msvc toolchain also provides a link.exe

**Comment by 1480c1** [comment]
FFmpeg's page on it (heavily outdated afaik because nobody does it, but it has some hints I think)
https://trac.ffmpeg.org/wiki/CompilationGuide/MSVC

> Now, make sure that the cl and link program are not override by other programs with the same name from MSYS/MinGW (in particular, note that MinGW provides a program named link). In order to do so, you can set the MSYS path so that the VisualStudio tools are used instead

Now, looking at your script, I think it's fine

**Comment by lazka** [comment]
Not sure if this is helpful, but I've used the following action to set up the MSVC build env successfully: https://github.com/harfbuzz/harfbuzz/blob/b37f03f16b39d397a626f097858e9ae550234ca0/.github/workflows/msvc-ci.yml#L30

I haven't mixed it with MSYS2 though.

**Comment by xmunoz** [comment]
> Not sure if this is helpful, but I've used the following action to set up the MSVC build env successfully: https://github.com/harfbuzz/harfbuzz/blob/b37f03f16b39d397a626f097858e9ae550234ca0/.github/workflows/msvc-ci.yml#L30
> 
> I haven't mixed it with MSYS2 though.

I tried ilammy/msvc-dev-cmd@v1 with msys and it worked! Thanks for the suggestion.

**Comment by xmunoz** [comment]
For posterity, here is what my final config looked like:

```
     - name: Set up msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Set up msys
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
          path-type: inherit
      - name: Build project
        run: |
          # all my build commands
        shell: msys2 {0}
```

**Comment by Biswa96** [comment]
May I ask why?

**Comment by xmunoz** [comment]
> May I ask why?

Why what?

**Comment by Biswa96** [comment]
Why do you want to use MSVC in msys2?

**Comment by xmunoz** [comment]
That is above my pay grade. Maybe @tkralphs has an answer for you.

**Comment by tkralphs** [comment]
Are you asking why bother with MSVC at all or why use it from msys2?

I myself would be happy not to touch MSVC, but it is unfortunately widely used. Libraries built with MSVC are needed for all kinds of things, including building Python C extensions in Windows, etc. So the answer to the first question is just that users want libraries built with MSVC and we want people to use our codes. 

So, given the need to build such libraries, building in bash means that we can at least use the same exact build harness that we do for other platforms. The alternative is to maintain Visual Studio solution files or something like that, but that's a huge pain.  

Of course, I know the next question will probably be "why not CMake" :). There's a longer answer for that one.

**Comment by reuben** [comment]
We also have the same need at coqui-ai/STT - building Python native extensions. Using ilammy/msvc-dev-cmd and `path-type: inherit` works, if you make sure to deal with `link.exe` and `mingw32-make` path conflicts, as well as any other things that randomly pop up in the environment as the Github Actions Windows images get updated. It'd be nice to have a cleaner solution, if anyone knows one!

**Comment by Biswa96** [comment]
This project may help to run MSVC in wine https://github.com/mstorsjo/msvc-wine
