### ISSUE TITLE
error: not enough free disk space

### ISSUE THREAD

**Issue by drfiemost** [msys2/setup-msys2#136]
Trying to run a build using qt5 static and few more libs but I'm facing this error: 
```
  checking available disk space...
  error: Partition / too full: 2746279 blocks needed, 2627211 blocks free
  error: not enough free disk space
  error: failed to commit transaction (not enough free disk space)
  Errors occurred, no packages were upgraded.
  Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

This is the command from my workflow:
```
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          zip
          upx
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-mpg123
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-opusfile
          mingw-w64-x86_64-libgme
          mingw-w64-x86_64-libmpcdec
          mingw-w64-x86_64-wavpack
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-libbs2b
          mingw-w64-x86_64-libsidplayfp
          mingw-w64-x86_64-libopenmpt
          mingw-w64-x86_64-liblastfm
```

Is there a way around this? I see that the static qt package is quite big (6.13 GB)

**Comment by eine** [comment]
Some packages are built on MSYS2 developers' computers, precisely because disk size in CI is not large enough. That is the case of Qt. See packages with status "Manual build required" in https://packages.msys2.org/queue.

**Comment by lazka** [comment]
@eine We build on C: in our CI which has 80GB or so free, the main limit is the 6 hours.

I think it might be worth it moving our temporary MSYS2 install to C: and let users build on D: to reduce the risk of running out of disk space. What do you think?

**Comment by Biswa96** [comment]
How do you know that?

**Comment by lazka** [comment]
Do you mean the disk space status? By running `Get-PSDrive -PSProvider FileSystem` in CI.

**Comment by Biswa96** [comment]
I thought we are not allowed to do that get/set sneaky things in CI.

**Comment by jeremyd2019** [comment]
It would be better if it didn't, especially for self-hosted runners who may not be identical to the VMs that github provides.

For the i686 msys job I made, I leave my checkouts in the default place and use SUBST to get shorter paths, but that doesn't help with the disk space issue should it crop up for msys packages

**Comment by eine** [comment]
> @eine We build on C: in our CI which has 80GB or so free, the main limit is the 6 hours.

My bad. I was confused with Linux jobs, which have less than half that size. I reopened.

> I think it might be worth it moving our temporary MSYS2 install to C: and let users build on D: to reduce the risk of running out of disk space. What do you think?

You mean the same trick used in the 'Move Checkout' step of jobs from msys2/MINGW-packages? Maybe we can document it but not add it as a default/built-in feature?

**Comment by lazka** [comment]
> You mean the same trick used in the 'Move Checkout' step of jobs from msys2/MINGW-packages? Maybe we can document it but not add it as a default/built-in feature?

No, I mean the MSYS2 installation directory, not the checkout. We currently install it to `RUNNER_TEMP`. But as @jeremyd2019 pointed out `RUNNER_TEMP` is cleaned up by the self-hosted runner, so to continue supporting that we'd have figure something out (a place and how to clean it up..)

**Comment by eine** [comment]
If there is some use case which cannot be built now and which would work with that tweak, I think it would be worth. Otherwise, better not increase the maintenance burden. @drfiemost do you have figures about how much space you are missing?

**Comment by jeremyd2019** [comment]
I do know I hit that when trying to build/install RelWithDebugInfo LLVM/clang...
https://github.com/msys2/CLANG-packages/issues/34#issuecomment-820889210

**Comment by drfiemost** [comment]
> @drfiemost do you have figures about how much space you are missing?

I see only a reference to blocks, not sure about the exact size of the block:

`error: Partition / too full: 2746279 blocks needed, 2627211 blocks free`

**Comment by orgads** [comment]
> It would be better if it didn't, especially for self-hosted runners who may not be identical to the VMs that github provides.
> 
> For the i686 msys job I made, I leave my checkouts in the default place and use SUBST to get shorter paths, but that doesn't help with the disk space issue should it crop up for msys packages. Plus [msys2/msys2-runtime#42](https://github.com/msys2/msys2-runtime/pull/42) and upstream wants to break that for me ☹️

I don't *want* to break anything. I just ported a change from upstream. Sooner or later, you'll need to handle it. Will you create a revert patch when upgrading to next release?

Honestly, I don't really need this change. I just bumped into this issue when I ran cmake unit tests, so I reported it. But this is an important compatibility issue that should be handled this way or another.

If you disagree with Corinna, please continue the discussion. Describe your use-case and why this change breaks it, maybe suggest an alternative?

**Comment by jeremyd2019** [comment]
Sorry, I didn't mean to 'accuse' you personally.  It just seems sometimes like the universe conspires to break things I use.

**Comment by eine** [comment]
Option `location` was added in v2.6.0, which allows specifying the MSYS2 installation directory. See https://github.com/msys2/setup-msys2/blob/master/CHANGELOG.md#260---20211103.
