### ISSUE TITLE
Cache service responded with 500

### ISSUE THREAD

**Issue by chronoxor** [msys2/setup-msys2#183]
I have constantly returned cache service respond with error 500 for [one of my projects](https://github.com/chronoxor/CppTrader/runs/4492090234?check_suite_focus=true):
```
Run msys2/setup-msys2@v2
Restoring package cache...
  Error: getCacheEntry failed: Cache service responded with 500
```

Other projects with same github actions work fine!

**Comment by chronoxor** [comment]
Looks like the issue in [actions/cache](https://github.com/actions/cache) - https://github.com/actions/cache/issues/698

**Comment by lazka** [comment]
I hit it once too `getCacheEntry failed: connect ETIMEDOUT 13.107.42.16:443`

Maybe we should be more forgiving in that case?

**Comment by eine** [comment]
I think it might have been some temporary reliability issue on GitHub's side. @chronoxor is it still happening?

> Maybe we should be more forgiving in that case?

Is there an explicit way of filtering that error apart from string matching?

**Comment by lazka** [comment]
> > Maybe we should be more forgiving in that case?
> 
> Is there an explicit way of filtering that error apart from string matching?

Not sure. Since even official actions failed and this was a real problem on GH's end maybe we shouldn't.

**Comment by chronoxor** [comment]
The issue was fixed on [actions/cache](https://github.com/actions/cache) side! The issue can be closed. But I think it's good idea to continue somehow even if cache is not available.
