### ISSUE TITLE
clang32 repo missing

### ISSUE THREAD

**Issue by txtsd** [msys2/setup-msys2#215]
So this action allows an `msystem` value of `clang32`, however, there is no `clang32` repo when updating and installing packages, so it is unable to find any clang32 packages.

**Comment by txtsd** [comment]
This is the output in GHA

```
Installing additional packages through pacboy...
  C:\Windows\system32\cmd.exe /D /S /C D:\a\_temp\setup-msys2\msys2.cmd -c "'pacboy' '--noconfirm' '-S' '--needed' 'toolchain:z' 'cmake:z' 'ninja:z' 'qt5:z' 'ccache:z'"
  error: target not found: mingw-w64-clang-i686-toolchain
  error: target not found: mingw-w64-clang-i686-cmake
  error: target not found: mingw-w64-clang-i686-ninja
  error: target not found: mingw-w64-clang-i686-qt5
  error: target not found: mingw-w64-clang-i686-ccache
  Error: The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

**Comment by eine** [comment]
FTR:

```
   :: Synchronizing package databases...
   mingw32 downloading...
   mingw64 downloading...
   ucrt64 downloading...
   clang64 downloading...
   msys downloading...
```
https://github.com/msys2/setup-msys2/runs/6237237242?check_suite_focus=true#step:4:169

@lazka @jeremyd2019 do you know why clang32 and clangarm64 are missing when using pacman/pacboy to sync?

**Comment by lazka** [comment]
They are simply not enabled yet by default in MSYS2.

**Comment by eine** [comment]
Shall we enable them by default in the MSYS2 installation that this action provides?

**Comment by txtsd** [comment]
Please do. Or at least allow it to be toggled on.

**Comment by txtsd** [comment]
I've been trying to append the `clang32` repo to `/etc/pacman.conf` [here](https://github.com/msys2/setup-msys2/blob/2135bf793478235b21bb12f979b00d281c5ebaa9/main.js#L280), but I'm unable to get `sed` or `echo` to do the job when newlines are involved in `runMsys()` arguments.

**Comment by eine** [comment]
https://github.com/msys2/setup-msys2/blob/main/CHANGELOG.md#2101---20220501

**Comment by txtsd** [comment]
Do I have to use a commit tag instead of `@v2` to have this feature?

**Comment by lazka** [comment]
> They are simply not enabled yet by default in MSYS2.

I've created https://github.com/msys2/MSYS2-packages/pull/2963
