### ISSUE TITLE
Disable CheckSpace independent of update: true

### ISSUE THREAD

**Issue by fabiangreffrath** [msys2/setup-msys2#241]
Hi,

could you please disable pacman's CheckSpace [1] "feature" independent of the `update` flag being set or not? I usually run the MSYS2 CI with `update` disabled, but install some additional packages afterwards and *then* I get bitten by this.

[1] https://github.com/msys2/setup-msys2/blob/d6c80756f2de6fb4438ffea3a4b1f1fe47ccae57/main.js#L276

Thanks!

**Comment by lazka** [comment]
Sounds good
