### ISSUE TITLE
Why are UCRT64 and CLANG64 "experimental"?

### ISSUE THREAD

**Issue by oscarbenjamin** [msys2/setup-msys2#270]
The README shows that msystem can be set to ucrt64 or clang64 but the comments in the examples describe those as being experimental.

It seems that these options were added over a year ago (https://github.com/msys2/setup-msys2/issues/125, #130) so are they still considered to be experimental?

**Comment by lazka** [comment]
Those notes can probably removed now, thanks.

**Comment by kmilos** [comment]
Also, shouldn't the default `msystem` now be `ucrt64`?

**Comment by lazka** [comment]
> Also, shouldn't the default `msystem` now be `ucrt64`?

that would be a breaking change

**Comment by kmilos** [comment]
Makes sense... So, for `v3` then?

**Comment by lazka** [comment]
yeah
