### ISSUE TITLE
Use a dummy startGroup at the start

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#28]
Currently the first login shell is created for disabling CheckSpace which includes all the first time things that get run. Haven an empty login shell at the start would make it easier to see which stage takes which amount of time.

**Comment by eine** [comment]
The initial purpose was to save a "useless" first run, if other commands are to be executed anyway. That's why `uname -a` was only executed when `update: false`. However, I get your point and I think it is fair.
