### ISSUE TITLE
"powershell.exe" renamed to "pwsh.exe"

### ISSUE THREAD

**Issue by stefantalpalaru** [msys2/setup-msys2#300]
The windows-2019 image no longer has "powershell.exe": https://github.com/actions/runner-images/issues/7516

**Comment by lazka** [comment]
Looking at your job logs it looks like you replace the PATH env var, maybe that's the cause?

We could try to get rid of powershell all together though, as there is no reason we couldn't do the same task with plain javascript.

**Comment by stefantalpalaru** [comment]
> you replace the PATH env var

You're right! Fixed by appending new paths to $GITHUB_PATH instead of trying to use $GITHUB_ENV.

Thank you!
