### ISSUE TITLE
Tag releases with semver tag

### ISSUE THREAD

**Issue by rturner3** [msys2/setup-msys2#327]
Some projects prefer to pin GitHub Actions dependencies by commit SHA rather than major version tag to prevent possible release pipeline vulnerabilities if a malicious tag is pushed to an external project.

If you pin the dependency on this action by commit SHA rather than major version tag, e.g. `v2`, dependabot doesn't ever detect minor release version updates, seemingly because:

- The existing major version tag changes to point to a different commit, which doesn't get detected by dependabot
- There is no version tag containing the full semver tag, e.g. `v2.20.0`, there is only a release branch, and dependabot seems to only detect new releases when new _tags_ are added to a repository

Other GitHub Actions tag their releases with full semver tags, and this is not a problem with those projects, e.g. [actions/checkout](https://github.com/actions/checkout).

Going forward, it would be really nice if each release had a semver tag so that projects depending on this step could get automatic update PRs sent by dependabot.

**Comment by lazka** [comment]
thanks, sounds good. I'll have a look.

**Comment by lazka** [comment]
Done now.

For future reference:

* I've merged all separate release branches into one branch here: https://github.com/msys2/setup-msys2/commits/dist
* I've added tags for all releases on that branch
* I've renamed the old release branches from "vX.Y.Z" to "legacy-vX.Y.Z" to keep the old commits reachable and avoid naming conflicts with the new tags
* I've released [v2.20.1](https://github.com/msys2/setup-msys2/releases/tag/v2.20.1) just now with some minor updates to test the release process

**Comment by rturner3** [comment]
Hmm, I didn't see that dependabot raised a PR for the new release. Perhaps you have to create a [GitHub release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) for the new releases to get noticed by dependabot?

**Comment by lazka** [comment]
done

**Comment by lazka** [comment]
From what I see it still didn't work (??)
