### ISSUE TITLE
pacman fails due to dependency conflict

### ISSUE THREAD

**Issue by daviwil** [msys2/setup-msys2#33]
Here's a new error that just started showing up in our CI builds:

```
  :: Starting core system upgrade...
  warning: terminate other MSYS2 programs before proceeding
  resolving dependencies...
  looking for conflicting packages...
  error: failed to prepare transaction (could not satisfy dependencies)
  :: installing filesystem (2020.02-3) breaks dependency 'msys2-base' required by dash
  ##[error]The process 'C:\windows\system32\cmd.exe' failed with exit code 1
```

https://github.com/gambit/gambit/runs/800489774#step:3:183

Perhaps something changed recently in MSYS2 that caused this?

**Comment by eine** [comment]
Hi @daviwil! I'm trying to understand why is this happening. It seems that this is an issue with caching. However, in our test suite, the cache is always saved in the first job, before running others. Hence, it should always be up to date with upstream...

**Comment by Hamayama** [comment]
Hello. I found a similar log here.
https://github.com/shirok/Gauche/runs/802663871#step:6:37

In this case, workflow file doesn't use setup-msys2
https://github.com/shirok/Gauche/blob/15f12ecffd29b38c6d63bb53a20299e1ceb0c547/.github/workflows/build.yml

So, another problem might be exist ...

**Comment by selsta** [comment]
I’ve found the issue to only happen when setting update to true. Did not seem cache related but could be wrong here.

**Comment by eine** [comment]
@Hamayama, @selsta, you are correct. I tried `pacman -Syu` locally and also a freshly extracted tarball from https://github.com/msys2/msys2-installer/releases/tag/2020-06-02, and both of them work. Hence, a new release might be required. @lazka?

**Comment by lazka** [comment]
should be fixed now. sorry :/
