### ISSUE TITLE
ctest fails as test-binaries are missing, even though cmake-build of those binaries shows no error

### ISSUE THREAD

**Issue by panchaBhuta** [msys2/setup-msys2#331]
For the workflow [windows-gnu-2.yml](https://github.com/panchaBhuta/converter/blob/6e57980a123bb3530e3ad6fd7fa686c692bc7f00/.github/workflows/windows-gnu-2.yml), the test 'testBasicConversions' fails.

The cause of failure [Could not find executable ... testBasicConversions](https://github.com/panchaBhuta/converter/actions/runs/6239680609/job/16938117711)
Though the debug-build does not pop any error messages, but the expected binaries are not getting generated either.

Could anyone take a look if this is a bug, or I am missed some config-settings.
Since I am new to workflows(as well as msys2), it likely to be latter.

Grepping the web didn't yield any helpful pointers.

Would appreciate if someone takes a look and if this is not a bug , point out what settings did I missed.

Thanks

**Comment by lazka** [comment]
No idea either, works fine locally.

Maybe pass the target name to add_test(), so cmake builds the path?
