### ISSUE TITLE
sometimes action is very slow

### ISSUE THREAD

**Issue by ognevnydemon** [msys2/setup-msys2#346]
I have set up action that uses msys2 for building Cargo project. most recent workflows went very long because setup-msys2 took ~3 minutes (compared to ~1.5 mins that was before). 

maybe it's GitHub issue, but I want to let you know

**Comment by Biswa96** [comment]
Could you compare the time in CI log to find exactly which step(s) took more time?

**Comment by ognevnydemon** [comment]
> Could you compare the time in CI log to find exactly which step(s) took more time?

the same workflow

slow: https://github.com/ognevnydemon/ognlib/actions/runs/7301001096/job/19896742737
normal: https://github.com/ognevnydemon/ognlib/actions/runs/7301001096/job/19896743164

**Comment by ognevnydemon** [comment]
in [this](https://github.com/ognevnydemon/MINGW-packages/actions/runs/7369726256/job/20055428021) action it ran 4.5 minutes!

**Comment by dimitre** [comment]
I also noticed this: 
https://github.com/openframeworks/openFrameworks/actions/workflows/build-msys2.yml
it would be great if we had an elapsed time for each step of the action to see which parts take more time.
Thank you

**Comment by Biswa96** [comment]
> it would be great if we had an elapsed time for each step of the action to see which parts take more time.

The raw CI log has timestamps prepended with every line.

**Comment by jeremyd2019** [comment]
In my case it seemed to be taking time after the last line in the step's log, before starting the next step.

**Comment by lazka** [comment]
Comparing various slow and fast jobs, the difference seems to be that only jobs which upload the cache hang at the end.

**Comment by lazka** [comment]
Downgrading to node16 seems to fix it :(

**Comment by lazka** [comment]
Upstream issue https://github.com/actions/toolkit/issues/1578

**Comment by lazka** [comment]
new release is out
