### ISSUE TITLE
Winget Update problem

### ISSUE THREAD

**Issue by bfcns** [msys2/setup-msys2#359]
Can you please clarify this:
https://github.com/microsoft/winget-pkgs/issues/127282

**Comment by ognevny** [comment]
AFAIK winget isn't officially supported from MSYS2 side

**Comment by Biswa96** [comment]
> do you ever need to install it again from the installer for an upgrade, or `pacman -Syu` is enough

`pacman -Syu` is enough. The idea is true for other rolling release projects also.

**Comment by lazka** [comment]
We have it documented here: https://www.msys2.org/docs/updating/ If there are things which should be more clear or highlighted more, let us know.

**Comment by lazka** [comment]
Yes, everything except the start menu files pointing to them.

**Comment by Biswa96** [comment]
> Does `pacman -Syuu` also upgrade the exe terminal files directly under C:\msys64, like msys2.exe etc?

msys2.exe etc. are part of [msys2-launcher](https://packages.msys2.org/package/msys2-launcher?repo=msys&variant=x86_64) package. So, those files will be updated like other packages when a newer version is available. Though, msys2-launchers are small programs and hardly changed.

**Comment by lazka** [comment]
I assume there is nothing else to do here. If not let us know.
