### ISSUE TITLE
Verify the checksum of the installer

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#36]
Would be nice to have because you never know :)

There is an issue for downloadTool() already here, but no progress: https://github.com/actions/toolkit/issues/427

**Comment by eine** [comment]
I found two commands to compute the checksum on Windows:

- `CertUtil -hashfile FILE SHA256`
- `Get-FileHash FILE  -Algorithm SHA256 | Format-List -Property Hash`

The output of the second one seems easier to parse and compare.

However, are checksums of the assets available anywhere apart from https://www.msys2.org/#installation-prerequisites?

**Comment by lazka** [comment]
> However, are checksums of the assets available anywhere apart from https://www.msys2.org/#installation-prerequisites?

It doesn't really matter where you get them from (you can also use sha256sum locally), just hardcode them when you change the installer URL so everybody gets the same and the installer can't change.

**Comment by eine** [comment]
I added a basic check (https://github.com/msys2/setup-msys2/commit/05abb8d585d071301cc19e6177945011875d9479) in the latest release. Thanks to @Paebbels for the help with powershell syntax ;)

However, I'll leave this issue open because I want to enhance the code.

**Comment by lazka** [comment]
Thanks!
