### ISSUE TITLE
Add cache-from and cache-to options

### ISSUE THREAD

**Issue by Xpl0itU** [msys2/setup-msys2#376]
I have a workflow that gets triggered whenever I create a tag, however, the created cache only works for that tag, and not other tags or any other run at all, see this SO post for what I mean: https://stackoverflow.com/questions/74113734/share-gha-docker-cache-among-branches

**Comment by lazka** [comment]
cache-from and cache-to are docker features. I don't understand what this has to do with this action.

**Comment by lazka** [comment]
See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache for cache isolation details.

All tags are isolated. We can't change anything about that.
