### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#39]
It would be nice if we'd get a new release out using 20200629 so we start with a fresh keyring.

I can create one too if wanted (I'd follow the steps in the README)

**Comment by eine** [comment]
Will do ASAP. I just have a doubt: will updating to 20200629 fix the issues that have been reported in the chat?

**Comment by lazka** [comment]
> will updating to 20200629 fix the issues that have been reported in the chat?

yes (the update issue, where things got reverted for now..)

**Comment by eine** [comment]
Done. I added a quick test of the checksum (#36) and I published a new release.

**Comment by lazka** [comment]
Thank you!
