### ISSUE TITLE
MSYS2_PATH_TYPE default

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#41]
The default in MSYS2 is "minimal" aka MSYS2 directories + default Windows directories. setup-msys2 defaults to "strict" which might be unexpected (things like cmd.exe are not available).

I wonder if changing the default now would still be possible.

**Comment by eine** [comment]
It might, but it may not be desirable. Virtual environments provided by GitHub do include Git for Windows, which is added to the PATH by default. Incidentally, VSCode supports Git for Windows only, and they refuse to support MSYS2. I don't know whether a relation exists between both facts.

The point is that the default environment contains potentially conflicting tools, such as `tar`, `git`, `ssh`, etc. Unless we can guarantee that none of those is included in the `minimal` context, I'd prefer users to be aware that MSYS2 is strictly that: MSYS2/MINGW.

FWIW, an option is provided: https://github.com/msys2/setup-msys2#path-type

**Comment by lazka** [comment]
https://github.com/msys2/MSYS2-packages/blob/915946a637e1f2b7e26e32782f3af322009293db/filesystem/profile#L28

It only adds those things which are in PATH on a fresh Windows install.

**Comment by eine** [comment]
I picked your PR and modified it to change the default path-type to `minimal`. According to your last reference, I think it is an acceptable change for `v1.2.0`.

> I suspect various tools expect those directories to be in PATH, but I'm also not sure because I've never worked in such an environment.

As a matter of fact, option path-type was added because some user needed it when using another action to setup golang: numworks/setup-msys2#13.
