### ISSUE TITLE
Maybe skip "gpg: refreshing 13 keys"

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#45]
Continuing my journey to nitpick everything. I hope that's OK.

So, on the first start we have:

```
Sun, 12 Jul 2020 22:28:19 GMT   gpg: refreshing 13 keys from hkps://hkps.pool.sks-keyservers.net
Sun, 12 Jul 2020 22:28:19 GMT   gpg: key 794DCF97F93FC717: "Martell Malone (martell) <me@martellmalone.com>" not changed
Sun, 12 Jul 2020 22:28:22 GMT   gpg: key FA11531AA0AA7F57: "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 4DF3B7664CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key D595C9AB2C51581E: 1 signature not checked due to a missing key
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key D595C9AB2C51581E: "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 974C8BE49078F532: "David Macek <david.macek.0@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 5F92EFC1A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 9F418C233E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 755B8182ACD22879: "Christoph Reiter (MSYS2 master key) <reiter.christoph@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key BBE514E53E0D0813: 1 signature not checked due to a missing key
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key BBE514E53E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key DA7EF2ABAEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key 790AE56A1D3CFDDC: "David Macek (MSYS2 master key) <david.macek.0@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: key F40D263ECA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" not changed
Sun, 12 Jul 2020 22:28:30 GMT   gpg: Total number processed: 12
Sun, 12 Jul 2020 22:28:30 GMT   gpg:              unchanged: 12
````

Which means 11 seconds lost for basically no change. (the thing executed here is this I think: https://github.com/msys2/MSYS2-packages/blob/3a99587ca16686fd0e2e74ffacabd2be15dd85ae/filesystem/07-pacman-key.post#L7)

I wonder if we should somehow skip that part. If we ever need to update the existing keys before an update we can always push out a new installer and update the action to use it. I haven't thought about how to skip it yet.

**Comment by lazka** [comment]
On a second thought, https://keyserver.ubuntu.com/pks/lookup?search=0x974C8BE49078F532&fingerprint=on&op=index has an expiration date, so without the refresh things would stop working on 2021-06-19 and we'd need a new installer after the key is extended again.

**Comment by eine** [comment]
> Continuing my journey to nitpick everything. I hope that's OK.

It's absolutely ok!

> I wonder if we should somehow skip that part. If we ever need to update the existing keys before an update we can always push out a new installer and update the action to use it. I haven't thought about how to skip it yet.

Maybe we should have some environment variable to customize this and other similar details. That would allow to skip all of them, but force the "default" behaviour when we need it. From the Action, we can decide when to set/unset that variable by checking some api/file/release. I guess any API call will take a second.

Moreover, skipping these kind of checks can be the default behaviour when `CI` is set. Then, we can use `FORCE_CHECKS` o `FULL_UPDATE` to force them.
