### ISSUE TITLE
Getting error "Inappropriate ioctl for device" upon various commands within msys shell

### ISSUE THREAD

**Issue by ComFreek** [msys2/setup-msys2#49]
For example, in [this recent build log of mine](https://github.com/ComFreek/curv/runs/886623620?check_suite_focus=true#step:3:329), the error of the subject line is printed upon running the action `msys2/setup-msys2` itself:
![image](https://user-images.githubusercontent.com/1827709/87871812-f2ea6d00-c9b3-11ea-8354-a631ea1715fc.png)

```
Installing additional packages...
  C:\windows\system32\cmd.exe /D /S /C D:\a\_temp\msys\msys2.cmd pacman --noconfirm -S --needed git diffutils mingw-w64-x86_64-clang make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-mesa mingw-w64-x86_64-openexr mingw-w64-x86_64-intel-tbb mingw-w64-x86_64-glm mingw-w64-x86_64-glew mingw-w64-x86_64-dbus patch mingw-w64-x86_64-openvdb
  
  D:\a\curv\curv>setlocal
  bash: cannot set terminal process group (-1): Inappropriate ioctl for device
  bash: no job control in this shell
  resolving dependencies...
  looking for conflicting packages...
```

The same error message is printed upon the following action:

```
- shell: msys2 {0}
  run: git describe --dirty
```

In all cases, the message seems to be just printed; the build continues normally.

PS: This is great action, very easy to use -- in comparison to how one needs to install/configure MSYS2 on Travis! Thanks for developing! :smile:

**Comment by lazka** [comment]
This is fixed in master and will be in the next update.

**Comment by lazka** [comment]
v2 is out now, make sure to switch things to `msys2/setup-msys2@v2`

(we had to do some potentially breaking changes, so a new version was required)
