### ISSUE TITLE
Lost files in the cache

### ISSUE THREAD

**Issue by lazka** [msys2/setup-msys2#61]
I managed to get a file lost in our cache here: https://github.com/msys2/msys2-devtools/runs/942546549?check_suite_focus=true

`pacman -Qkq` checks if all files that should be there are there and one was missing

I'm not sure how and why, and how likely. Let's watch out for similar cases..

**Comment by jeremyd2019** [comment]
It might be useful (definitely while working on the this action, but apparently maybe for others) to have an option to not use (or maybe just not restore, to replace) the cache

**Comment by lazka** [comment]
I'd prefer if it just worked :)

**Comment by lazka** [comment]
It happened again now:

```
pacman -Qkq
mingw-w64-x86_64-headers-git /mingw64/x86_64-w64-mingw32/include/tapi.h
```

**Comment by lazka** [comment]
The cache was created in https://github.com/msys2/msys2-devtools/runs/972534368?check_suite_focus=true and restored in https://github.com/msys2/msys2-devtools/runs/972714924?check_suite_focus=true. After the cache save the file was still there so I'd guess cache store is buggy.

**Comment by lazka** [comment]
happened again. I think we have to disable the caching sadly.
