### ISSUE TITLE
Upgrading often fails due to outdated mirrors

### ISSUE THREAD

**Issue by startaq** [msys2/setup-msys2#82]
Our CI often fails on the upgrade step. Examples:

https://github.com/mamedev/mame/runs/1307764572?check_suite_focus=true
https://github.com/mamedev/mame/runs/1305338802?check_suite_focus=true
https://github.com/mamedev/mame/runs/1302390352?check_suite_focus=true

Our workflow file is here: https://github.com/mamedev/mame/blob/master/.github/workflows/ci-windows.yml

Can package upgrades be delayed until at least some mirrors have the packages?

**Comment by lazka** [comment]
From what we know the problem is that sourceforge takes some time to sync mirrors (which we don't control) and doesn't do so in the order we upload things. So there is a 15 min window where things might be out of sync after a repo update.

**Comment by johnny-bit** [comment]
so the workaround is to not use "update"?

**Comment by lazka** [comment]
Or retry the build since this only happens every few days and lasts for half an hour or so.

**Comment by lazka** [comment]
We've worked this around now by first syncing only the packages to sourceforge and only after 30 minutes the DB files, so ideally sourceforge has time to sync everything to their mirrors before pacman tries to download them.

Also we are in the process of moving away from sourceforge. If it happens again please report.
