### ISSUE TITLE
Action fails to use correct shell for calling cmake dependencies

### ISSUE THREAD

**Issue by johnny-bit** [msys2/setup-msys2#84]
I'm trying to use GH actions over travis builds since gh is significantly faster, however I'm running into issues. Our cmake-based build systems depends on calling couple mingw external apps, such as intltool-merge, however build proceeds using cmd instead of msys2.

PR and build woes can be seen here: https://github.com/darktable-org/darktable/pull/6603

I'm open to any suggestion on how to improve build system to work :)

**Comment by lazka** [comment]
(I don't know much about cmake)

* What about the "MSYS Makefiles"? Maybe that doesn't use cmd.exe.
* Otherwise you can find "perl" and somehow execute intltool stuff with perl.
* port away from intltool to gettext ;) (I know it's tricky..)

**Comment by johnny-bit** [comment]
Intltool seems to be part of base devel stuff, but better safe than sorry. I'm checking MSYS Makefiles generator and in last case will try running intltool with perl... damn, why normal windows build works but on CI it's "fun"time ;)

**Comment by lazka** [comment]
https://github.com/msys2/MINGW-packages/pull/7206 64bit of the last release seems to work fine (also using this action)

**Comment by johnny-bit** [comment]
Yup, Ninja as generator was the problem maker. Thanks!
