### ISSUE TITLE
Using environment based paths with msys2

### ISSUE THREAD

**Issue by jwillemsen** [msys2/setup-msys2#94]
In our github action we are using environment variables pointing to the location of a cloned directory, for example

```
    env:
      ACE_ROOT: ${{ github.workspace }}/ACE
```

When we now later use msys2 `cp` it fails because the path is now `D:aACE_TAOACE_TAO/ACE` because the env is a windows path. 

Would be nice if there is a way to indicate which environment variables should be converted to msys2 paths in some ways when using the msys2 shell

**Comment by eine** [comment]
@jwillemsen you can convert paths between Windows and Unix formats with `cygpath`. See https://cygwin.com/cygwin-ug-net/cygpath.html.

**Comment by jwillemsen** [comment]
Yes, I found that, thinking more, I could execute cygpath in the run step before the real commands, will try that, maybe something for an example in this project

**Comment by jwillemsen** [comment]
Yes, using cygpath within the run step works, see https://github.com/DOCGroup/ACE_TAO/blob/c62ecd5955c1350fa25f95deb9bce2c81bc70f1c/.github/workflows/windows.yml#L198
